### PR TITLE
ipyvizzu.Chart.animation: allow distinct animations

### PR DESCRIPTION
**Pull request by nyirog**
All Animation has a main key (Data => "data", Config => "config")
therefore it is quite straightforward to merge different animation in
one `Chart.animate` call. Therefore `Chart.animate` can allow multiple
animations until they do not override any data.

The `*animations` and `**config` can be merged with this strategy, too
and the *args and **kwargs calls will lokk similar:

  Chart().animate(config={...}, data={...})

  Chart().animate(Config(...), Data(...))

### CODE REVIEW

**Comment by veghdev** [comment]
In this solution if I see weel, AnimationMerger() will also merges the below examples:

`chart.animate(Config({"align": "center"}), geometry="circle")`

`chart.animate(config={"align": "center"}, geometry="circle")`

But Vizzu animate call can not handle kwargs (config=, style=, data=) and kwargs (config elements without config like geometry=, x=, y=, etc) together.

**Comment by nyirog** [comment]
Yes `AnimationMerger` does not know anything about the semantic of the vizzu API. Do you think it would be safer to handle `*animations` and  `**config` as two distinct solution and do not merge them?

**Comment by veghdev** [comment]
Yes, I think one option is completely disable *animations and **config merging;
or the other option is enable merging, but validate first level's data
- contains style and/or data and/or config only
- contains anything else except style, data, config

**Comment by veghdev** [comment]
What do you think about these modifications below:

It allows:
Chart.animate(Config({...}), Data({...}))
Chart.animate(Config({...}), data={...})
Chart.animate(config={...}, data={...})
Chart.animate(title="title")

It does not allow:
Chart.animate(config={...}, title={...})
Chart.animate(Config({...}), title={...})

`class Chart:

def animate(self, *animations: Animation, **config):
        """
        Register new animation.
        """
        animation = self._merge_animations(animations, config)
        self._calls.append(Animate(animation))
        
 def _merge_animations(self, animations, config):
        merger = AnimationMerger()
        merger.merge(PlainAnimation(config))
        for animation in animations:
            merger.merge(animation)

        anim_types = {'config', 'style', 'data'}
        if not merger.keys() <= anim_types \
            and any(anim_type in merger.keys() for anim_type in anim_types):
                 raise ValueError(
                    "`animations` and `config` cannot be used together."
                )

        return merger
`

**Comment by veghdev** [comment]
yes, for now

**Comment by simzer** [comment]
The JS API accepts the following arguments:
animate({ data, config, style }, animoptions)
animate(config, animoptions)
animate({ data, config, style })
animate(config)

**Pull request merged**
