### PR TITLE
docs: examples generator scripts

### PR DESCRIPTION
**Pull request by simzer**
Usage:
```
cd tools/example-generator
npm intall
pip install -r requirements.txt
./run.sh
```
Sparse clones/checks out the vizzu-lib repo to the current folder.
Generates ipynb files for each example file found in the vizzu-lib repo
`test/integration/test_cases/web_content/sample_static/*.mjs`,
`test/integration/test_cases/web_content/templates/*.mjs`
into `docs/examples/static`, `docs/examples/animated` folders

### CODE REVIEW

**Comment by simzer** [comment]
Known problems:
- Should checkout specific commit corresponding the vizzu version used by ipyvizzu instead of HEAD

**Comment by simzer** [comment]
@nyirog @veghdev 
The examples are dependent on ~450KB CSV data files, should I commit them into this repo or what to do?
Alternatively, I could create a new data repo and put them there.

**Comment by simzer** [comment]
CSV generator added too.

**Comment by nyirog** [comment]
On Sat, Mar 26, 2022, 11:55 PM Laszlo Simon ***@***.***>
wrote:

> @nyirog <https://github.com/nyirog> @veghdev <https://github.com/veghdev>
> The examples are dependent on ~450KB CSV data files, should I commit them
> into this repo or what to do?
>

I think git can handle ~450kB csv data easily. As far it is not part of the
pipy package it should not bother the end user.

If someone checkout the git repo for play a bit with the source code.
He/she will have a complex dataset, too. So I think the large csv file can
add extra value to the development experience.

Regards,
Gergo

**Comment by simzer** [comment]
well, i have already made a converter which generates the csv from the js data files.

**Pull request merged**
